name = "MO_Registry"
uuid = "218a0020-e4ce-469c-a7a4-c3e8c7987179"
repo = "git@github.com:manuelbb-upb/MO_Registry.git"
description = "Private Julia registry for various projects/packages related to mulitobjective optimization"

[packages]
88936782-c8cd-4a0f-b259-ffb12bfd2869 = { name = "Morbit", path = "M/Morbit" }
ad069600-9bf0-4bd3-b060-bd43ee6ba39c = { name = "MultiObjectiveProblems", path = "M/MultiObjectiveProblems" }
